### ISSUE TITLE
[APP] i would like to make texture 👍 

### ISSUE THREAD

**Issue by telaphone99** [Cixon/project4j#1]
# What do you prefer to help with?
minor block/mob textures (maybe models) and such

**Your Projects/Work:**
a1.2.6 texture pack (originally made for a minecraft clone) i'll have to dm you an image of the things made for it

**I understand I will be credited if approved and may or may not make a profit**
input 'x' in box.
i dont want to make a profit off of anything and i cant anyway
- [x] Yes
- [] No

**Comment by telaphone99** [comment]
I didnt realize github let you post images bruh im a fucking idiot
![image](https://github.com/user-attachments/assets/d1110bcc-7136-4d73-9ffa-4316a7cf4bae)
![image](https://github.com/user-attachments/assets/799a5b72-82d4-4032-a26c-3819844621dd)

**Comment by Cixon** [comment]
I really like the art style, would you be open to assisting in adding mod-support for [Plastic Texture pack](https://modrinth.com/resourcepack/plastic-texture-pack)? It’s bundled with P4J but no mod-support for Terrestria or Twilight forest.

**Comment by Cixon** [comment]
ren via L4J discord.
